# Generated by Django 4.2.4 on 2023-10-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=models.TextField(default='h'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='expertise',
            field=models.TextField(default='k'),
            preserve_default=False,
        ),
    ]
