# Generated by Django 4.2.4 on 2023-10-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completed_date',
            field=models.DateTimeField(),
        ),
    ]
